# Generated by Django 3.2 on 2023-03-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230323_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='person',
            new_name='persons',
        ),
    ]
